// Auto-generated by dex-creator. Do not edit.
// Committed as an empty stub so fresh clones typecheck; deploy pipeline
// overwrites it with installed plugin imports per DEX.
export const dexPlugins = [] as const;
